[package]
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "ch4-p081"
publish = false
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version = "0.0.0-SNAPSHOT"

[dependencies]
anyhow = { workspace = true }
candle-core = { workspace = true }
csv = { workspace = true }
